-- Setup file for database
-- This file should only be run once, in case of cloning the production database schema
-- onto your local development machine
-- The production database *must* be exactly reproducible by this setup file
-- For high access contributors, manual database maintenance can be performed via credentials
-- Note that this file does not insert any data into the database, it simply props up the necessary relation schema

CREATE TABLE IF NOT EXISTS accounts (
    username TEXT PRIMARY KEY,                -- Username, primary
    email TEXT NOT NULL,                      -- User's email
    password TEXT NOT NULL,                   -- Hash of the password
    full_name TEXT NOT NULL,                  -- Full name of user
    created_on DATE,                          -- Account creation date
    activated BOOLEAN DEFAULT FALSE           -- Account activation status (default false for all new accounts)
);

CREATE TABLE IF NOT EXISTS inactive_accounts (
    username TEXT NOT NULL,
    activationToken TEXT NOT NULL,
    CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES accounts(username)
);

CREATE TABLE IF NOT EXISTS posts (
    post_id SERIAL PRIMARY KEY, -- Auto-generated post id
    post_author TEXT NOT NULL,       -- Post author username
    post_type TEXT NOT NULL CHECK(
            post_type IN ('TEXT_POST', 'LINK_POST', 'IMAGE_POST', 'VIDEO_POST')
    ),                               -- Type of post - Text, Link, Image, or Video
    post_title TEXT NOT NULL,        -- Title of the post
    post_body TEXT NOT NULL,         -- Body of the post
        -- For text posts, content will be the entire body of the post
        -- For link posts, content will be the target URL
        -- For image posts, content will be the Image URL
        -- For video posts, content will be the Video URL
    post_tags TEXT[4] DEFAULT '{}', -- Post tags, for SEO / metadata searching
        -- Allow only upto 4 tags, no more!
        -- Just a precautionary measure, I don't think we'll need many tags
        -- Some tags might be autogenerated in case of no tags provided
    post_modified_date DATE NOT NULL,
        -- Date on which post was created / edited, auto generated by db
    post_like_count INTEGER DEFAULT 0,
    edited BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_post_author_username FOREIGN KEY (post_author) REFERENCES accounts(username)
        -- author username foreign key, we'll be pulling other author info
        -- from the accounts table.
);

CREATE TABLE IF NOT EXISTS comments (
    comment_id SERIAL PRIMARY KEY,              -- Comment ID
    comment_author TEXT NOT NULL,               -- Author's username
    comment_parent_post INTEGER NOT NULL,       -- Parent post ID
    comment_type TEXT NOT NULL CHECK (
        comment_type IN ('ROOT', 'REPLY')       -- ROOT : Top-level comment
                                                -- REPLY : Nested comment
    ),
    comment_body TEXT NOT NULL,
    comment_like_count INTEGER DEFAULT 0,
    comment_reply_parent INTEGER DEFAULT NULL,  -- Parent comment ID if comment is a reply

    CONSTRAINT fk_comment_reply_parent FOREIGN KEY (comment_reply_parent) REFERENCES comments (comment_id),
    CONSTRAINT fk_comment_author_username FOREIGN KEY (comment_author) REFERENCES accounts(username),
    CONSTRAINT fk_comment_parent_post FOREIGN KEY (comment_parent_post) REFERENCES posts(post_id)

)