-- Setup file for database
-- This file should only be run once, in case of cloning the production database schema
-- onto your local development machine
-- The production database *must* be exactly reproducible by this setup file
-- For high access contributors, manual database maintenance can be performed via heroku secret credentials
-- Note that this file does not insert any data into the database, it simply props up the necessary relation schema

CREATE TABLE IF NOT EXISTS users (
    username TEXT PRIMARY KEY,                -- Username, primary
    email TEXT NOT NULL,                      -- User's email
    password TEXT NOT NULL,                   -- Hash of the password
    full_name TEXT NOT NULL,                  -- Full name of user
    created_on DATE,                          -- Account creation date
    activated BOOLEAN DEFAULT FALSE           -- Account activation status (default false for all new accounts)
);

CREATE TABLE IF NOT EXISTS inactive_users (
    username TEXT NOT NULL,
    verificationToken TEXT NOT NULL,
    CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users(username)
);

CREATE TABLE IF NOT EXISTS posts (
    post_id SERIAL PRIMARY KEY, -- Auto-generated post id
    author TEXT NOT NULL,       -- Post author username
    post_type TEXT NOT NULL CHECK(
            post_type IN ('TEXT_POST', 'LINK_POST', 'IMAGE_POST', 'VIDEO_POST')
    ),                          -- Type of post - Text, Link, Image, or Video
    title TEXT NOT NULL,        -- Title of the post
    body TEXT NOT NULL,         -- Body of the post
        -- For text posts, content will be the entire body of the post
        -- For link posts, content will be the target URL
        -- For image posts, content will be the Image URL
        -- For video posts, content will be the Video URL
    tags TEXT[4] DEFAULT '{}', -- Post tags, for SEO / metadata searching
        -- Allow only upto 4 tags, no more!
        -- Just a precautionary measure, I don't think we'll need many tags
        -- Some tags might be autogenerated in case of no tags provided
    date_created DATE NOT NULL,
        -- Date on which post was created, auto generated by db
    like_count INTEGER DEFAULT 1,
    CONSTRAINT fk_author_username FOREIGN KEY (author) REFERENCES users(username)
        -- author username foreign key, we'll be pulling other author info
        -- from the users table.
);